input.onButtonPressed(Button.A, function () {
    basic.showIcon(IconNames.Happy)
    pins.digitalWritePin(DigitalPin.P2, 1)
    soundExpression.happy.playUntilDone()
    basic.pause(500)
    basic.clearScreen()
    pins.digitalWritePin(DigitalPin.P2, 0)
})
input.onSound(DetectedSound.Loud, function () {
    pins.digitalWritePin(DigitalPin.P8, 1)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.pause(1000)
    pins.digitalWritePin(DigitalPin.P8, 0)
    pins.digitalWritePin(DigitalPin.P2, 1)
})
input.onButtonPressed(Button.B, function () {
    basic.showIcon(IconNames.Surprised)
    pins.digitalWritePin(DigitalPin.P8, 1)
    soundExpression.mysterious.playUntilDone()
    basic.pause(500)
    basic.clearScreen()
    pins.digitalWritePin(DigitalPin.P8, 0)
})
pins.digitalWritePin(DigitalPin.P2, 1)
